# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-28 12:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Promise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('C', 'Completed'), ('WIP', 'In Progress'), ('NS', 'Not Started'), ('B', 'Broken')], default='NS', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='PromiseGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Representative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('join_data', models.DateTimeField()),
                ('end_data', models.DateTimeField()),
                ('position', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=300)),
                ('phone', models.IntegerField()),
                ('webmail', models.EmailField(max_length=254)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.Board')),
            ],
        ),
        migrations.AddField(
            model_name='promisegroup',
            name='representative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.Representative'),
        ),
        migrations.AddField(
            model_name='promise',
            name='promisegroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.PromiseGroup'),
        ),
        migrations.AddField(
            model_name='promise',
            name='representative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.Representative'),
        ),
    ]
