# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-28 12:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='name',
            new_name='title',
        ),
    ]
