# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-28 13:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0007_auto_20160528_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='board',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='poll.Board'),
        ),
        migrations.AlterField(
            model_name='club',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='representative',
            name='board',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='poll.Board'),
        ),
        migrations.AlterField(
            model_name='representative',
            name='club',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='poll.Club'),
        ),
    ]
