# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-28 13:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0008_auto_20160528_1317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='representative',
            name='club',
        ),
    ]
