# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-28 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0011_club_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=b'clubs/'),
        ),
    ]
