# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-29 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0012_auto_20160528_2006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='board',
        ),
        migrations.RemoveField(
            model_name='representative',
            name='club',
        ),
        migrations.AddField(
            model_name='board',
            name='sorder',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Club',
        ),
    ]
