# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-29 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0013_auto_20160529_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='representative',
            name='sub_board',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
