# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-29 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0015_representative_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='representative',
            name='degree',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='representative',
            name='dept',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='representative',
            name='year',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
