# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-29 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0016_auto_20160529_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='representative',
            name='end_data',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='representative',
            name='join_data',
            field=models.DateField(),
        ),
    ]
